services:
  db:
    container_name: db
    image: postgres:17
    environment:
      POSTGRES_DB: db_v1
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user_password
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - db_network

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:9.3
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - '8080:80'
    networks:
      - db_network

volumes:
  db_data:

networks:
  db_network:
    driver: bridge
